### ISSUE TITLE
Cards requiring link

### ISSUE THREAD

**Issue by bcsj** [Salem2612/anrsealed#10]
I generated a pool of cards an encountered something I think is a slight issue. I was given Underworld Contact and 4 cards which raise link, however 3 of them were consoles, rendering the Underworld Contact nearly blank. I don't know if this is a card pool issue per se. Maybe it wouldn't break the sealed runner id to give it link 1, but I guess some consideration should go into that.

**Comment by Salem2612** [comment]
Hello and thank you for your comment. There are 2 explanations of your issue:
 1. Some picked cards can be unusable. I tried to ban most cards that require others cards to work. Underworld Contact is maybe the last card of this kind that I let available because it's a money card. If it works in a Sealed Pack it's good, if not don't play it in your Deck.
 2. The algorithm don't take into account the cards that are picked to create combos between them.

I don't want to give the Runner 1 link because it will break all Traces of the Corp to make a single card completely useful. I would prefer to ban Underworld Contact if it is useless in all Sealed Pack, instead of breaking all Corp Traces.

So I'm sorry for your bad pick. It's 1 card among 85. If you think that Underworld Contact will be useless in all picked Sealed Pack, I can consider banishing it.

**Comment by bcsj** [comment]
Hi, thanks for your reply and explanation. Since I posted this I also saw your reasoning for these cards in the Netrunner Sealed thread on the Stimhack forums. It is probably fine to leave it in the pool for the occasional pool supporting it. Version 3.0 upgrade looks good.

**Comment by Salem2612** [comment]
I hope you'll like it ^^
