### ISSUE TITLE
Econ Cards

### ISSUE THREAD

**Issue by 5N00P1** [Salem2612/anrsealed#15]
Got in a pack Desperado & Paragon which is ok by itself, I just ask myself if they are treated as economy cards? As they are econ cards, that force you to run.

**Comment by Salem2612** [comment]
All the types of the cards are given in this Google Sheet:
https://docs.google.com/spreadsheets/d/1iODcruMiN18QsMhlUhh8vzwSrZUXHVB_TKxhVQNRNdM/edit?usp=sharing

Desperado & Paragon are not marked as ECO cards. ECO cards don't give infinite credits. Magnum Opus and Kati Jones have been banned because they gave infinite and non interactive credits. Paragon is just marked as a Console. Desperado is also marked as BROKEN because it is ^^
