### ISSUE TITLE
4 Consoles in one Deck

### ISSUE THREAD

**Issue by ghost** [Salem2612/anrsealed#16]
Have the following consoles in one deck:
- Desperado
- Paragon
- Spinalmodem
- Comet
Not sure if that is a but to much?

**Comment by Salem2612** [comment]
Which Mode did you select ? Sealed or Deck ?
 - In Sealed, the algorithm picks at least 2 Consoles (without maximum). You then build a deck among the 85 picked cards. Picking 4 Consoles give you the choice of what you want to use.
 - In Deck Mode, the algorithm picks between 2 and 3 Consoles. So if it's the Mode you used, there is a bug.

**Comment by 5N00P1** [comment]
Sure in Sealed where you need selections this makes sense. Sorry it's a sealed deck. I'll attach.
[Sealed Pack - Player 8 - Runner - Starter.txt](https://github.com/Salem2612/anrsealed/files/2629647/Sealed.Pack.-.Player.8.-.Runner.-.Starter.txt)

**Comment by Salem2612** [comment]
Desperado as a BROKEN CONSOLE have been added to the mandatory 2-3 COMMON CONSOLES you picked. It's a bug, because it causes your deck to have 4 CONSOLES that is a bit too much. I'll fix it.

The file you send has others problems:
 1. The Deck has no IDENTITY card. It should have 1.
 2. The Deck has 43 cards. It should have 46 (45 + the ID).
Did you send me the whole Deck ? Do you have the log.txt file that is at the root of the ZIP file ? It gives more information about the picking.

**Comment by 5N00P1** [comment]
TY, yes it should be the whole one.

attached the log.

[log.txt](https://github.com/Salem2612/anrsealed/files/2629767/log.txt)

**Comment by Salem2612** [comment]
Thx. The bug were here:
`  - Guinea Pig [COMMON] [CARD] [ECO] [NEWBIE] (Among 78 cards)`
Guinea Pig is not marked as EVENT and so not listed in the EVENTs. I'll fix it and check the whole cardpool.

Try Ctrl+F5 on the website before the next generating to include the ID at the beginning of the TXT file.

**Comment by Salem2612** [comment]
I fixed the bug of the number of CONSOLEs in Sealed Decks. It is now between 2 and 3 even with the BROKEN CONSOLEs.
>      {"types":["CONSOLE","COMMON"],"min":2,"max":3},
>      {"types":["CONSOLE"],"min":2,"max":3},
